<h1><center><b>NUMPY ARRAY PRACTICE</b></center></h1>

<h2><b>Contents </b></h2>
    
   <font><ol><li>Creating ndarray</li>
        <li>Data Types </li>
        <li>Arithmetic with Numpy </li>
        <li>Set </li>
        <li>List Comprehension</li>
        <li>Function</li>
        <li>Namespaces,Scope and Local Functions</li>
        <li>Function Objects</li>
        <li>File System </li>
        <li>Exception Handling </li>
    </ol></font>

In [1]:
import numpy as np #Importing numpy module

In [4]:
arr_np=np.arange(100000)
arr_list=list(range(100000))

In [7]:
%time for _ in range(10):arr_np=arr_np*2 #see output numpy is much more faster than normal list

CPU times: user 1.85 ms, sys: 1.35 ms, total: 3.2 ms
Wall time: 3.54 ms


In [8]:
%time for _ in range(10):[i*2 for i in arr_list]

CPU times: user 70.4 ms, sys: 5.39 ms, total: 75.8 ms
Wall time: 76.6 ms


## 1.Creating ndarray

In [10]:
d=np.random.randn(2,4) #randn will generate random number of floating point numbers
d

array([[-0.76837558,  0.09315759, -0.48556177,  0.14250522],
       [-0.60219706,  0.70208867, -1.76179505,  0.02974694]])

In [11]:
d*20

array([[-15.36751164,   1.86315179,  -9.71123534,   2.85010439],
       [-12.0439411 ,  14.04177346, -35.23590104,   0.59493882]])

In [15]:
list_d=[2,3,4,5,6,7,2,3,4]
aar_np=np.array(list_d) #Converting Numpy array of simple list
arr_np

array([        0,      1024,      2048, ..., 102396928, 102397952,
       102398976])

In [16]:
nest_list=[[10,120,11,32],[2,54,54,67]]
nump_arr=np.array(nest_list)     #converting into numpy array
nump_arr

array([[ 10, 120,  11,  32],
       [  2,  54,  54,  67]])

In [18]:
nump_arr.shape #For checking metrics size

(2, 4)

In [20]:
nump_arr.ndim   

2

## 2.Data Types

In [21]:
nump_arr.dtype

dtype('int64')

In [22]:
np.zeros(5) #generating 5 zeros

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,4)) #generating zeros with 2 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.arange(10) #array of range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.empty((2,3,2)) #generating 2 numpy array with 2 rows and 3 columns 

array([[[1.28822975e-231, 1.28822975e-231],
        [2.96439388e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[1.28822975e-231, 1.28822975e-231],
        [1.48219694e-323, 0.00000000e+000],
        [0.00000000e+000, 8.34402697e-309]]])

In [32]:
float_num=np.arange(10,dtype=np.float) #Genertaing floating type
float_num

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
np.arange(10,dtype=np.int64) #Genertaing integer type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
integer_num=float_num.astype(np.int64) #astype will convert the floating into desired type
integer_num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3.Arithmetic with Numpy

In [2]:
r=np.arange(20)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
s=np.arange(10,30)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [6]:
s+r

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [7]:
s-r

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10])

In [8]:
1/s

array([0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
       0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276])

In [9]:
1//s

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
%time r*s

CPU times: user 15 µs, sys: 1e+03 ns, total: 16 µs
Wall time: 19.1 µs


array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171, 200, 231, 264,
       299, 336, 375, 416, 459, 504, 551])

In [12]:
r[1:4]

array([1, 2, 3])

## 4.Transposing arrays and swapping axes

In [14]:
ar_new=np.arange(20).reshape(5,4) #one line array is transformed or transposed into 5x4
ar_new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
swap_ar=ar_new.T 
swap_ar#Here T is stand for tranposing the metric

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

## 5.UNIVERSAL FUNCTION

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays

In [21]:
ar=np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [24]:
a=np.random.randn(5)
b=np.random.randn(5)

In [25]:
a

array([ 0.11863003,  0.90566476, -0.11130499, -0.99617499, -0.11021392])

In [26]:
b

array([-1.07522134,  0.04542873, -0.24657799, -1.91713623,  0.52487992])

In [27]:
np.maximum(a,b) #Element wise maximum numbers

array([ 0.11863003,  0.90566476, -0.11130499, -0.99617499,  0.52487992])

In [28]:
c=np.random.randn(5)*10
c

array([-9.29119533, 10.13470319,  2.414125  ,  0.42922897, 18.52792016])

In [32]:
fractional,integral=np.modf(c) #modf will print integral and fractional part

In [33]:
fractional  #fractionl part

array([-0.29119533,  0.13470319,  0.414125  ,  0.42922897,  0.52792016])

In [31]:
integral  #Integral part

array([-9., 10.,  2.,  0., 18.])